// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSubscriptionCommand(arg1) {
  return window['go']['SubscriptionCommand']['subscriptionCommand']['CreateSubscriptionCommand'](arg1);
}

export function DeleteSubscriptionCommand(arg1) {
  return window['go']['SubscriptionCommand']['subscriptionCommand']['DeleteSubscriptionCommand'](arg1);
}

export function GetSubscriptionCommand(arg1) {
  return window['go']['SubscriptionCommand']['subscriptionCommand']['GetSubscriptionCommand'](arg1);
}

export function ListSubscriptionsCommand() {
  return window['go']['SubscriptionCommand']['subscriptionCommand']['ListSubscriptionsCommand']();
}

export function UpdateSubscriptionCommand(arg1) {
  return window['go']['SubscriptionCommand']['subscriptionCommand']['UpdateSubscriptionCommand'](arg1);
}
