// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {commandUtils} from '../models';

export function CreateSubscriptionCommand(arg1:domain.CreateSubscriptionRequest):Promise<commandUtils.Response>;

export function DeleteSubscriptionCommand(arg1:domain.DeleteSubscriptionRequest):Promise<commandUtils.Response>;

export function GetSubscriptionCommand(arg1:domain.GetSubscriptionRequest):Promise<commandUtils.Response>;

export function ListSubscriptionsCommand():Promise<commandUtils.Response>;

export function UpdateSubscriptionCommand(arg1:domain.UpdateSubscriptionRequest):Promise<commandUtils.Response>;
