/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompanyList: typeof import('./components/CompanyList.vue')['default']
    CreateCompany: typeof import('./components/dialogs/CreateCompany.vue')['default']
    CreateSubscription: typeof import('./components/dialogs/CreateSubscription.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscriptionList: typeof import('./components/SubscriptionList.vue')['default']
  }
}
