// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {commandUtils} from '../models';

export function CreateCompanyCommand(arg1:domain.CreateCompanyRequest):Promise<commandUtils.Response>;

export function DeleteCompanyCommand(arg1:domain.DeleteCompanyRequest):Promise<commandUtils.Response>;

export function GetCompanyCommand(arg1:domain.GetCompanyRequest):Promise<commandUtils.Response>;

export function ListCompaniesCommand():Promise<commandUtils.Response>;

export function ListCompanySubscriptionsCommand(arg1:domain.ListCompanySubscriptionsRequest):Promise<commandUtils.Response>;

export function UpdateCompanyCommand(arg1:domain.UpdateCompanyRequest):Promise<commandUtils.Response>;
