// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCompanyCommand(arg1) {
  return window['go']['CompanyCommand']['companyCommand']['CreateCompanyCommand'](arg1);
}

export function DeleteCompanyCommand(arg1) {
  return window['go']['CompanyCommand']['companyCommand']['DeleteCompanyCommand'](arg1);
}

export function GetCompanyCommand(arg1) {
  return window['go']['CompanyCommand']['companyCommand']['GetCompanyCommand'](arg1);
}

export function ListCompaniesCommand() {
  return window['go']['CompanyCommand']['companyCommand']['ListCompaniesCommand']();
}

export function ListCompanySubscriptionsCommand(arg1) {
  return window['go']['CompanyCommand']['companyCommand']['ListCompanySubscriptionsCommand'](arg1);
}

export function UpdateCompanyCommand(arg1) {
  return window['go']['CompanyCommand']['companyCommand']['UpdateCompanyCommand'](arg1);
}
